command:
  - "python"
  - "app.py"

env:
  - name: LAKEBASE_SECRET_SCOPE
    value: "database"
  - name: LAKEBASE_SECRET_KEY
    value: "lakebase-url"
  - name: GITHUB_API_BASE_URL
    value: "https://api.github.com"
  - name: GITHUB_SECRET_SCOPE
    value: "github"
  - name: GITHUB_SECRET_KEY
    value: "token"
